/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controlador.CRelacionMateria;
import Modelos.MRelacionMateria;
import Modelos.MRelacionMaterias;
import javax.swing.JOptionPane;

/**
 *
 * @author yaxkin-pc
 */
public class RegistrarAlumnoMateria extends javax.swing.JInternalFrame {
    //MRelacionMateria mra=new MRelacionMateria();
    private CRelacionMateria cr=new CRelacionMateria();
    /**
     * Creates new form RegistrarAlumnoMateria
     */
    public RegistrarAlumnoMateria() {
        initComponents();
        limpiaCampos();
        //this.comboAlumno.setModel(cr.llenarCombo());
        //this.comboMateria.setModel(cr.llenarComboMateria());
    }

    void limpiaCampos(){
        cr.llenarComboAlumno();
        cr.llenarComboMaterias();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboMateria = new javax.swing.JComboBox<>();
        comboAlumno = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        comboMateria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        comboAlumno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton1.setText("ACEPTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(comboMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(comboAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButton1)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       //accion();
       int id=comboAlumno.getItemAt(comboAlumno.getSelectedIndex()).getIdAlumno();
       JOptionPane.showMessageDialog(null, id);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void accion(){
        if(comboAlumno.getSelectedItem().equals("ALUMNO") && comboMateria.getSelectedItem().equals("MATERIA")){
            JOptionPane.showMessageDialog(null, "Selecciona una materia y un estudiante.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }else{
            //mra
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<MRelacionMateria> comboAlumno;
    public static javax.swing.JComboBox<MRelacionMaterias> comboMateria;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
